language: python
python:
  # - "2.6" # Cannot pass CI due to Paramiko
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - autoshell -m crawl -h
